import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
group = []

if GetDepend('USE_MA35_RTP'):
    cwd = GetCurrentDir()
    src = []
    path = [cwd + '/Include',]
    group = DefineGroup('CMSIS', src, depend = [''], CPPPATH = path)

Return('group')
