# RT-Thread building script for component

import rtconfig
Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()
CPPPATH = [ cwd ]
src = Glob('entry_point.S')
group = DefineGroup('board', src, depend = ['USE_PRELOADER'], CPPPATH = CPPPATH)

Return('group')
